<div class="footer-external">
    <div class="footer-breaker"></div>
        <div class="footer-internal light-text">
            <div class="col-half">
                <div class="info">
                    <h3>Navigation</h3>
                    <a href="index.html">Home</a> | <a href="">Contact</a> | <a href="">About</a>
					<h3>Information</h3>
					<p>This website was produced for acadamic purposes.</p>
                </div>
            </div>
            <div class="col-half">
                <div class="info">
                    <h3>Author</h3>
                    <p>Name: Greg Mills</p>
					<p>Student Number: n9165029</p>
					<p>Subject: CAB230</p>
                </div>
            </div>
        </div>
    </div>